@BLogProject_HostAddress = https://localhost:7102

GET {{BLogProject_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{BLogProject_HostAddress}}/api/author
Authorization: Bearer CfDJ8CQBTFQvdSZIrcB8SDzSN2cogAml1kwHlgvVH1UqPJlyKSNkYXgfbrXpXinGhyC5Wk4uezlJOToxloRnOFHaSj1AC28FxMgboZyt582MxKc0u1iTE4EjgS6eBE_cXeVeqmep1YRjRBWBuBLYa-JXyhMhUF3hUKARABfgxbVIfteklBU7hrWsuefpf7dnB4UbSd2dPxo0FbYk18ROBo1GL-yRl_4MOiC2e7FUBlFQ_a17AQve5BjBsUHOEoJg_1X31GxqNHStnENkfdUcwNlqnhysn-nZ9jjZMMGkcUgchnK363tDuxA09a_3d9uiMFFDhP71lttt2jAWmp7ax2_0hnRvGrSxphRzg423YkxZkrw8YNLIDxlrnWCRJ9hhi9v4pNWLuX2mG7XxtyV7OdcdDDdq1fxhQC7bittjPi65irgw5iO06QpCU716ULw8kxn6pAfIHnZ3L7HnQLUD9nBtZcu6d-r-jMzjHYcrYEFzVjWfJXZ_DjFU-Xj0EwdIRUrXuJUFETn5AlrYeNtJcFlHPsQ2iQsC1Hztf0q2r08qD0odUIL2DBHU48v55XYDZ2mZDNmsUhPzjUS5QfvSDoK68hS4qhubiQdITNeX7ToLITcZIauY6bRjZG2tz8K6N4NP4RI-BTI0sMblp4DLwvsAcy8TSobnD5VeQVYm2D4UZQrbBLJZBTVbj1WosTMotp3K_xSSdFlRwVa1PDjqG1lbLOs

###
